// 初始化菜单（扁平结构，parentId 对应 id）
module.exports = [
    {
        id: 1,
        parentId: null,
        name: '',
        path: '/platform',
        component: 'Layout',
        redirect: '/platform/tenant',
        title: '平台管理',
        icon: 'el-icon-Platform',
        hidden: false,
        alwaysShow: false,
        keepAlive: null,
        params: null,
        sort: 1,
        perm: null,
        type: 'C',
        scope: 1,
        visible: 1
    },
    {
        id: 110,
        parentId: 1,
        name: 'Tenant',
        path: 'tenant',
        component: 'system/tenant/index',
        redirect: null,
        title: '租户管理',
        icon: 'el-icon-OfficeBuilding',
        hidden: false,
        alwaysShow: false,
        keepAlive: true,
        params: null,
        sort: 1,
        perm: null,
        type: 'M',
        scope: 1,
        visible: 1
    },
    {
        id: 1101,
        parentId: 110,
        name: '',
        path: '',
        component: null,
        redirect: null,
        title: '租户查询',
        icon: '',
        hidden: false,
        alwaysShow: false,
        keepAlive: null,
        params: null,
        sort: 1,
        perm: 'sys:tenant:list',
        type: 'B',
        scope: 1,
        visible: 1
    },
    {
        id: 1102,
        parentId: 110,
        name: '',
        path: '',
        component: null,
        redirect: null,
        title: '租户新增',
        icon: '',
        hidden: false,
        alwaysShow: false,
        keepAlive: null,
        params: null,
        sort: 2,
        perm: 'sys:tenant:create',
        type: 'B',
        scope: 1,
        visible: 1
    },
    {
        id: 230,
        parentId: 1,
        name: 'SysMenu',
        path: 'menu',
        component: 'system/menu/index',
        redirect: null,
        title: '菜单管理',
        icon: 'menu',
        hidden: false,
        alwaysShow: false,
        keepAlive: true,
        params: null,
        sort: 2,
        perm: null,
        type: 'M',
        scope: 1,
        visible: 1
    },
    {
        id: 2301,
        parentId: 230,
        name: '',
        path: '',
        component: null,
        redirect: null,
        title: '菜单查询',
        icon: '',
        hidden: false,
        alwaysShow: false,
        keepAlive: null,
        params: null,
        sort: 1,
        perm: 'sys:menu:list',
        type: 'B',
        scope: 1,
        visible: 1
    },
    {
        id: 2,
        parentId: null,
        name: '',
        path: '/system',
        component: 'Layout',
        redirect: '/system/user',
        title: '系统管理',
        icon: 'system',
        hidden: false,
        alwaysShow: false,
        keepAlive: null,
        params: null,
        sort: 2,
        perm: null,
        type: 'C',
        scope: 2,
        visible: 1
    },
    {
        id: 210,
        parentId: 2,
        name: 'User',
        path: 'user',
        component: 'system/user/index',
        redirect: null,
        title: '用户管理',
        icon: 'el-icon-User',
        hidden: false,
        alwaysShow: false,
        keepAlive: true,
        params: null,
        sort: 1,
        perm: null,
        type: 'M',
        scope: 2,
        visible: 1
    },
    {
        id: 3,
        parentId: null,
        name: '',
        path: '/codegen',
        component: 'Layout',
        redirect: '/codegen/index',
        title: '代码生成',
        icon: 'code',
        hidden: false,
        alwaysShow: false,
        keepAlive: null,
        params: null,
        sort: 3,
        perm: null,
        type: 'C',
        scope: 2,
        visible: 1
    },
    {
        id: 310,
        parentId: 3,
        name: 'Codegen',
        path: 'codegen',
        component: 'codegen/index',
        redirect: null,
        title: '代码生成',
        icon: 'code',
        hidden: false,
        alwaysShow: false,
        keepAlive: true,
        params: null,
        sort: 1,
        perm: null,
        type: 'M',
        scope: 2,
        visible: 1
    }
];
